name: Build & Publish

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get version
        run: echo "latest=${GITHUB_REF##*/}"" >> $GITHUB_ENV
      - name: build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository}}:${{ env.latest }}
            ghcr.io/${{ github.repository}}:latest
    outputs:
      version: ${{ env.latest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: clone infra
        uses: actions/checkout@v3
        with:
          repository: qntfrd/infra
          path: infra
          token: ${{ secrets.QNTFRD_PAT }}
          submodules: true

      - name: get base image
        run: echo "image=`echo ${{ github.repository }} | cut -d '/' -f 2`" >> $GITHUB_ENV

      - name: bump infra
        run: |
          sed -i -E "s/${{ env.image }}:[0-9]+(\.[0-9]+){2}/${{ env.image }}:${{ needs.build.outputs.version }}/g" infra/docker/production.yml
          cd infra/apps/${{ env.image }}
          git checkout ${{ needs.build.outputs.version }}
          cd ../..

      - name: deploy infra
        run: |
          cd infra
          git config --global user.email "ci@lio.dev"
          git config --global user.name "Lio CI/CD"
          git commit -am "chore(bump): ${{github.repository}} to ${{ needs.build.outputs.version }}"
          git push
